<a href="https://colab.research.google.com/github/yashghogre/First-ML-Model/blob/main/Model_Selection_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Logistic Regression

In [5]:
from sklearn.linear_model import LogisticRegression
clf_log = LogisticRegression(random_state = 0)
clf_log.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [6]:
y_pred_log = clf_log.predict(X_test)

In [7]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_log = confusion_matrix(y_test, y_pred_log)
print(cm_log)
acc_log = accuracy_score(y_test, y_pred_log)
print(acc_log)

[[84  3]
 [ 3 47]]
0.9562043795620438


K-Nearest Neighbor

In [8]:
from sklearn.neighbors import KNeighborsClassifier
clf_knn = KNeighborsClassifier(n_neighbors = 5, metric= 'minkowski', p = 2)
clf_knn.fit(X_train, y_train)

KNeighborsClassifier()

In [9]:
y_pred_knn = clf_knn.predict(X_test)

In [10]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_knn = confusion_matrix(y_test, y_pred_knn)
print(cm_knn)
acc_knn = accuracy_score(y_test, y_pred_knn)
print(acc_knn)

[[83  4]
 [ 2 48]]
0.9562043795620438


svc linear

In [11]:
from sklearn.svm import SVC
clf_svc = SVC(kernel = 'linear', random_state = 0)
clf_svc.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [12]:
y_pred_svc = clf_svc.predict(X_test)

In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_svc = confusion_matrix(y_test, y_pred_svc)
print(cm_svc)
acc_svc = accuracy_score(y_test, y_pred_svc)
print(acc_svc)

[[83  4]
 [ 2 48]]
0.9562043795620438


svc non linear

In [14]:
from sklearn.svm import SVC
clf_ker = SVC(kernel = 'rbf', random_state = 0)
clf_ker.fit(X_train, y_train)

SVC(random_state=0)

In [15]:
y_pred_ker = clf_ker.predict(X_test)

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_ker = confusion_matrix(y_test, y_pred_ker)
print(cm_ker)
acc_ker = accuracy_score(y_test, y_pred_ker)
print(acc_ker)

[[82  5]
 [ 1 49]]
0.9562043795620438


Naive Bayes

In [17]:
from sklearn.naive_bayes import GaussianNB
clf_nb = GaussianNB()
clf_nb.fit(X_train, y_train)

GaussianNB()

In [18]:
y_pred_nb = clf_nb.predict(X_test)

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_nb = confusion_matrix(y_test, y_pred_nb)
print(cm_ker)
acc_nb = accuracy_score(y_test, y_pred_nb)
print(acc_nb)

[[82  5]
 [ 1 49]]
0.948905109489051


Decision Tree

In [20]:
from sklearn.tree import DecisionTreeClassifier
clf_dt = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
clf_dt.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [21]:
y_pred_dt = clf_dt.predict(X_test)

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_dt = confusion_matrix(y_test, y_pred_dt)
print(cm_dt)
acc_dt = accuracy_score(y_test, y_pred_dt)
print(acc_dt)

[[85  2]
 [ 2 48]]
0.9708029197080292


Random Forest Classification

In [23]:
from sklearn.ensemble import RandomForestClassifier
clf_rf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
clf_rf.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [24]:
y_pred_rf = clf_rf.predict(X_test)

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_rf = confusion_matrix(y_test, y_pred_rf)
print(cm_rf)
acc_rf = accuracy_score(y_test, y_pred_rf)
print(acc_rf)

[[84  3]
 [ 3 47]]
0.9562043795620438


Surprisingly! Decision Tree beats Random Forest Classification here.