<a href="https://colab.research.google.com/github/yashghogre/First-ML-Model/blob/main/r2_testing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Multiple Linear**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('Data.csv')
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [4]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)
y_pred_lin = lin_reg.predict(X_test)
y_pred_lin

array([431.42761597, 458.56124622, 462.75264705, ..., 469.51835895,
       442.41759454, 461.88279939])

In [6]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_lin)

0.9325315554761303

**Decision Tree**

In [7]:
from sklearn.tree import DecisionTreeRegressor
dec_reg = DecisionTreeRegressor(random_state = 0)
dec_reg.fit(X_train, y_train)
y_pred_dec = dec_reg.predict(X_test)
y_pred_dec

array([431.28, 459.59, 460.06, ..., 471.46, 437.76, 462.74])

In [8]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_dec)

0.922905874177941

**Random Forest Regression**

In [9]:
from sklearn.ensemble import RandomForestRegressor
rf_reg = RandomForestRegressor(n_estimators = 10, random_state = 0)
rf_reg.fit(X_train, y_train)
y_pred_rf = rf_reg.predict(X_test)
y_pred_rf

array([434.049, 458.785, 463.02 , ..., 469.479, 439.566, 460.385])

In [10]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_rf)

0.9615908334363876

**Polynomial Linear Regression**

In [13]:
from sklearn.preprocessing import PolynomialFeatures
poly_feat = PolynomialFeatures(degree = 4)
poly_feat.fit(X_train)
X_pf = poly_feat.transform(X_train)
X_pf_test = poly_feat.transform(X_test)
X_pf

array([[1.00000000e+00, 1.12200000e+01, 4.31300000e+01, ...,
        6.77242028e+09, 5.38603280e+08, 4.28345379e+07],
       [1.00000000e+00, 1.36700000e+01, 5.43000000e+01, ...,
        5.87072958e+09, 4.35831980e+08, 3.23553508e+07],
       [1.00000000e+00, 3.28400000e+01, 7.79500000e+01, ...,
        2.15967876e+09, 9.74822477e+07, 4.40009357e+06],
       ...,
       [1.00000000e+00, 1.68100000e+01, 3.85200000e+01, ...,
        5.86500714e+09, 4.33197009e+08, 3.19964912e+07],
       [1.00000000e+00, 1.28000000e+01, 4.11600000e+01, ...,
        7.76570573e+09, 6.54642544e+08, 5.51858229e+07],
       [1.00000000e+00, 3.23200000e+01, 6.79000000e+01, ...,
        1.45623249e+09, 5.49010997e+07, 2.06981424e+06]])

In [16]:
from sklearn.linear_model import LinearRegression
pol_reg = LinearRegression()
pol_reg.fit(X_pf, y_train)
y_pred_pol = pol_reg.predict(X_pf_test)
y_pred_pol

array([433.94385411, 457.90455377, 460.52460138, ..., 469.52889978,
       438.26543131, 461.6649096 ])

In [18]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_pol)

0.9458192809530098

**Support Vector Regression**

In [20]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_svr = sc_X.fit_transform(X_train)
y_svr = sc_y.fit_transform(y_train.reshape(-1, 1))
X_svr

array([[-1.13572795, -0.88685592,  0.67357894,  0.52070558],
       [-0.80630243, -0.00971567,  0.45145467,  0.14531044],
       [ 1.77128416,  1.84743445,  0.24279248, -1.88374143],
       ...,
       [-0.38409993, -1.24886277,  0.84522042,  0.13092486],
       [-0.9232821 , -1.04155299,  1.54693117,  0.8830852 ],
       [ 1.70136528,  1.05824381, -1.20438076, -2.42285818]])

In [25]:
from sklearn.svm import SVR
svr_reg = SVR(kernel = 'rbf')
svr_reg.fit(X_svr, y_svr)
y_pred_svr = svr_reg.predict(sc_X.transform(X_test))
sc_y.inverse_transform(y_pred_svr.reshape(-1, 1))

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[434.05242921],
       [457.93810186],
       [461.03113894],
       ...,
       [470.60268461],
       [439.41653548],
       [460.91757115]])

In [31]:
from sklearn.metrics import r2_score
# r2_score(sc_y.inverse_transform(y_svr).reshape(-1, 1), sc_y.inverse_transform(y_pred_svr).reshape(-1, 1))
r2_score(y_test, sc_y.inverse_transform(y_pred_svr.reshape(-1, 1)))

0.9480784049986258