<a href="https://colab.research.google.com/github/yashghogre/First-ML-Model/blob/main/Sample_Apple_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [40]:
data = pd.read_csv('apple_quality.csv')
data = data.dropna()
X = data.iloc[:, 1:-1].values
y = data.iloc[:, -1].values

In [41]:
# from sklearn.preprocessing import OneHotEncoder
# from sklearn.compose import ColumnTransformer
# ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(drop = 'if_binary'), [0])], remainder = 'passthrough')
# y = np.array(ct.fit_transform(y.reshape(-1, 1)))

In [42]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [43]:
y

array([1, 1, 0, ..., 0, 1, 1])

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [45]:
from sklearn.linear_model import LogisticRegression
clf_log = LogisticRegression()
clf_log.fit(X_train, y_train)
y_pred_log = clf_log.predict(X_test)

In [46]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_log = confusion_matrix(y_test, y_pred_log)
print(cm_log)
acc_log = accuracy_score(y_test, y_pred_log)
print(acc_log)

[[310 112]
 [ 86 292]]
0.7525


In [47]:
from sklearn.neighbors import KNeighborsClassifier
clf_knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
clf_knn.fit(X_train, y_train)
y_pred_knn = clf_knn.predict(X_test)

In [48]:
cm_knn = confusion_matrix(y_test, y_pred_knn)
print(cm_knn)
acc_knn = accuracy_score(y_test, y_pred_knn)
print(acc_knn)

[[363  59]
 [ 28 350]]
0.89125


In [49]:
from sklearn.svm import SVC
clf_svclin = SVC(kernel= 'linear', random_state = 0)
clf_svclin.fit(X_train, y_train)
y_pred_svclin = clf_svclin.predict(X_test)

In [50]:
cm_svclin = confusion_matrix(y_test, y_pred_svclin)
print(cm_svclin)
acc_svclin = accuracy_score(y_test, y_pred_svclin)
print(acc_svclin)

[[302 120]
 [ 81 297]]
0.74875


In [51]:
from sklearn.svm import SVC
clf_svcker = SVC(kernel = 'rbf', random_state = 0)
clf_svcker.fit(X_train, y_train)
y_pred_svcker = clf_svcker.predict(X_test)

In [52]:
cm_svcker = confusion_matrix(y_test, y_pred_svcker)
print(cm_svcker)
acc_svcker = accuracy_score(y_test, y_pred_svcker)
print(acc_svcker)

[[364  58]
 [ 26 352]]
0.895


In [53]:
from sklearn.naive_bayes import GaussianNB
clf_nb = GaussianNB()
clf_nb.fit(X_train, y_train)
y_pred_nb = clf_nb.predict(X_test)

In [54]:
cm_nb = confusion_matrix(y_test, y_pred_nb)
print(cm_nb)
acc_nb = accuracy_score(y_test, y_pred_nb)
print(acc_nb)

[[308 114]
 [ 86 292]]
0.75


In [55]:
from sklearn.tree import DecisionTreeClassifier
clf_dt = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
clf_dt.fit(X_train, y_train)
y_pred_dt = clf_dt.predict(X_test)

In [56]:
cm_dt = confusion_matrix(y_test, y_pred_dt)
print(cm_dt)
acc_dt = accuracy_score(y_test, y_pred_dt)
print(acc_dt)

[[340  82]
 [ 76 302]]
0.8025


In [61]:
from sklearn.ensemble import RandomForestClassifier
clf_rf = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 0)
clf_rf.fit(X_train, y_train)
y_pred_rf = clf_rf.predict(X_test)

In [62]:
cm_rf = confusion_matrix(y_test, y_pred_rf)
print(cm_rf)
acc_rf = accuracy_score(y_test, y_pred_rf)
print(acc_rf)

[[367  55]
 [ 33 345]]
0.89
